### ISSUE TITLE
fix of VecTraits_T::End

### ISSUE THREAD

**Issue by githubmanticore** [nck-2/test-rep#228]
`VecTraits_T::End` code should be same as `VecTraits_T::end` as for now `Vec.End()` after `Vec.Add(1); Vec.Resize(0);` returns pointer that is NOT `nullptr` and could cause side effects such as crash of daemon at <a href ="https://gitlab.com/manticoresearch/dev/issues/1072">#1072</a> 
 
I've made a patch that I post below however it crashed daemon at ubertest 14 and after with following stack 
``` 
Сore was generated by `/home/stas/manticore/build/src/searchd --config /home/stas/manticore/build/test'. 
Program terminated with signal SIGSEGV, Segmentation fault. 
#0  0x0000000000a78467 in ExtMultiAnd_T<true, false>::GetDocsChunk (this=0x7ff304014cd0) at /home/stas/manticore/src/searchnode.cpp:2948 
2948                            pStoredHit->m_tRowID = tMatchedRowID; 
[Current thread is 1 (Thread 0x7ff30d182700 (LWP 29677))] 
(gdb) bt 
#0  0x0000000000a78467 in ExtMultiAnd_T<true, false>::GetDocsChunk (this=0x7ff304014cd0) at /home/stas/manticore/src/searchnode.cpp:2948 
#1  0x00000000009be72f in ExtRanker_T<true>::GetFilteredDocs (this=0x7ff3040140c0) at /home/stas/manticore/src/sphinxsearch.cpp:832 
#2  0x00000000009c4255 in ExtRanker_State_T<RankerState_Proximity_fn<true, false>, true>::GetMatches (this=0x7ff3040140c0) 
    at /home/stas/manticore/src/sphinxsearch.cpp:1019 
#3  0x00000000008026b8 in CSphIndex_VLN::MatchExtended<false, false, false> (this=0x2b8c940, pCtx=0x7ff30d17cfb0, pQuery=0x7ff3040028d8, iSorters=1, 
    ppSorters=0x7ff3040138b0, pRanker=0x7ff3040140c0, iTag=0, iIndexWeight=1) at /home/stas/manticore/src/sphinx.cpp:13841 
#4  0x00000000007b0b62 in CSphIndex_VLN::ParsedMultiQuery (this=0x2b8c940, pQuery=0x7ff3040028d8, pResult=0x7ff304003de8, iSorters=1, 
    ppSorters=0x7ff3040138b0, tXQ=..., pDict=0x7ff30ee65010, tArgs=..., pNodeCache=0x7ff30d17d570, tStatDiff=...) 
    at /home/stas/manticore/src/sphinx.cpp:17332 
#5  0x00000000007ae931 in CSphIndex_VLN::MultiQuery (this=0x2b8c940, pQuery=0x7ff3040028d8, pResult=0x7ff304003de8, iSorters=1, 
    ppSorters=0x7ff304013830, tArgs=...) at /home/stas/manticore/src/sphinx.cpp:16942 
#6  0x00000000007aebcf in CSphIndex_VLN::MultiQueryEx (this=0x2b8c940, iQueries=1, pQueries=0x7ff3040028d8, ppResults=0x7ff304012f00, 
    ppSorters=0x7ff304013830, tArgs=...) at /home/stas/manticore/src/sphinx.cpp:16963 
#7  0x00000000006827f3 in SearchHandler_c::RunLocalSearches (this=0x7ff30d17f260) at /home/stas/manticore/src/searchd.cpp:5902 
#8  0x000000000068664c in SearchHandler_c::RunSubset (this=0x7ff30d17f260, iStart=0, iEnd=0) at /home/stas/manticore/src/searchd.cpp:6649 
``` 
 
that should be also fixed and double checked all `Vec.End()` usage at our code.

**Comment by githubmanticore** [comment]
➤ Stan commented:
 

 
```diff 
 src/gtests/gtests_functions.cpp | 27 +++++++++++++++++++++++++++ 
 src/sphinxstd.h                 |  4 ++-- 
 2 files changed, 29 insertions(+), 2 deletions(-) 
 
diff --git a/src/gtests/gtests_functions.cpp b/src/gtests/gtests_functions.cpp 
index 1d9f5c02..1e847779 100644 
--- a/src/gtests/gtests_functions.cpp 
+++ b/src/gtests/gtests_functions.cpp 
@@ -2762,4 +2762,31 @@ TEST ( functions, path ) 
 	CSphString sSrc14 ( "/pq2" ); 
 	CSphString sFile14 = GetBaseName ( sSrc14 ); 
 	ASSERT_STREQ ( sFile14.cstr(), "pq2" ); 
+} 
+ 
+ 
+TEST ( functions, vector_begin_end ) 
+{ 
+	CSphVector<int> dVec; 
+	dVec.Add ( 10 ); 
+	ASSERT_EQ ( dVec.GetLength(), 1 ); 
+	dVec.Resize ( 0 ); 
+ 
+	ASSERT_TRUE ( dVec.IsEmpty() ); 
+	ASSERT_EQ ( dVec.GetLength(), 0 ); 
+	ASSERT_EQ ( dVec.Begin(), nullptr ); 
+	ASSERT_EQ ( dVec.End(), nullptr ); 
+	ASSERT_EQ ( dVec.begin(), nullptr ); 
+	ASSERT_EQ ( dVec.end(), nullptr ); 
+ 
+	dVec.Add ( 10 ); 
+	ASSERT_EQ ( dVec.GetLength(), 1 ); 
+	dVec.Reset(); 
+ 
+	ASSERT_TRUE ( dVec.IsEmpty() ); 
+	ASSERT_EQ ( dVec.GetLength(), 0 ); 
+	ASSERT_EQ ( dVec.Begin(), nullptr ); 
+	ASSERT_EQ ( dVec.End(), nullptr ); 
+	ASSERT_EQ ( dVec.begin(), nullptr ); 
+	ASSERT_EQ ( dVec.end(), nullptr ); 
 } 
\ No newline at end of file 
diff --git a/src/sphinxstd.h b/src/sphinxstd.h 
index 3f65e014..326bc053 100644 
--- a/src/sphinxstd.h 
+++ b/src/sphinxstd.h 
@@ -962,7 +962,7 @@ public: 
 	/// pointer to the item after the last 
 	T * End () const 
 	{ 
-		return  m_pData + m_iCount; 
+		return m_iCount ? m_pData + m_iCount : nullptr; 
 	} 
  
 	/// make happy C++11 ranged for loops 
@@ -973,7 +973,7 @@ public: 
  
 	T * end () const 
 	{ 
-		return m_iCount ? m_pData + m_iCount : nullptr; 
+		return End(); 
 	} 
  
 	/// get last entry 
```
